-- ============================================================
-- PINEWOOD SENIOR LIVING
-- GOLD STAR SCHEMA - DDL / GRAIN NOTES
-- ============================================================

-- This file documents the Gold-layer star schema.
-- The physical Gold tables are generated by pipeline/run_pipeline.py
-- and persisted to DuckDB / Parquet.
--
-- Grain notes are included for each table.
-- Data types below represent the intended analytical schema.


-- ============================================================
-- DIMENSIONS
-- ============================================================

CREATE TABLE dim_community (
    community_id VARCHAR,
    state VARCHAR,
    region VARCHAR
);

-- Grain: one row per community.
-- Primary key: community_id.
-- Used for community and regional filtering/RLS.


CREATE TABLE dim_date (
    date DATE,
    year INTEGER,
    month_number INTEGER,
    month_name VARCHAR,
    month_start DATE
);

-- Grain: one row per calendar date.
-- Primary key: date.
-- Used as the shared calendar dimension for time intelligence.


CREATE TABLE dim_resident (
    resident_id VARCHAR,
    community_id VARCHAR,
    admit_date DATE,
    discharge_date DATE,
    dob DATE,
    first_name VARCHAR,
    gender VARCHAR,
    last_name VARCHAR
);

-- Grain: one row per resident.
-- Primary key: resident_id.
-- Stores resident-level descriptive and admission/discharge attributes.


CREATE TABLE dim_unit (
    unit_id VARCHAR,
    community_id VARCHAR,
    unit_type VARCHAR
);

-- Grain: one row per unit.
-- Primary key: unit_id.


CREATE TABLE dim_care_level (
    care_level VARCHAR
);

-- Grain: one row per canonical care level.
-- Values:
--   Independent Living
--   Assisted Living
--   Memory Care


-- ============================================================
-- FACT TABLES
-- ============================================================

CREATE TABLE fact_resident_month (
    resident_id VARCHAR,
    community_id VARCHAR,
    care_level VARCHAR,
    acuity_score DOUBLE,
    snapshot_date DATE,
    snapshot_month VARCHAR
);

-- Grain: one resident snapshot per month.
-- Foreign keys:
--   resident_id   -> dim_resident
--   community_id  -> dim_community
--   care_level    -> dim_care_level
--   snapshot_date -> dim_date


CREATE TABLE fact_incident (
    incident_id VARCHAR,
    resident_id VARCHAR,
    community_id VARCHAR,
    incident_date DATE,
    incident_type VARCHAR,
    reported_by VARCHAR,
    severity DOUBLE
);

-- Grain: one incident event.
-- Primary key: incident_id.
-- Foreign keys:
--   resident_id  -> dim_resident
--   community_id -> dim_community
--   incident_date -> dim_date


CREATE TABLE fact_lease (
    lease_id VARCHAR,
    resident_id VARCHAR,
    unit_id VARCHAR,
    community_id VARCHAR,
    move_in_date DATE,
    move_out_date DATE,
    move_out_reason VARCHAR,
    monthly_rate DOUBLE
);

-- Grain: one lease transaction.
-- Primary key: lease_id.
-- Foreign keys:
--   resident_id  -> dim_resident
--   unit_id      -> dim_unit
--   community_id -> dim_community
--   move_out_date -> dim_date
--
-- The active Power BI date relationship uses move_out_date
-- because move-out analysis is a required business question.


CREATE TABLE fact_shift (
    shift_id VARCHAR,
    employee_id VARCHAR,
    community_id VARCHAR,
    role VARCHAR,
    shift_date DATE,
    hours_worked DOUBLE,
    hourly_rate DOUBLE,
    labor_cost DOUBLE
);

-- Grain: one employee shift.
-- Primary key: shift_id.
-- Foreign keys:
--   community_id -> dim_community
--   shift_date   -> dim_date


CREATE TABLE fact_review (
    review_id VARCHAR,
    community_id VARCHAR,
    review_date DATE,
    rating DOUBLE,
    review_text VARCHAR,
    response_text VARCHAR,
    responded_at DATE
);

-- Grain: one Google Business Profile review.
-- Primary key: review_id.
-- Foreign keys:
--   community_id -> dim_community
--   review_date  -> dim_date


CREATE TABLE fact_lead (
    lead_id VARCHAR,
    community_id VARCHAR,
    lead_source VARCHAR,
    created_date DATE,
    tour_date DATE,
    deposit_date DATE,
    move_in_date DATE,
    status VARCHAR,
    lost_reason VARCHAR
);

-- Grain: one HubSpot lead.
-- Primary key: lead_id.
-- Foreign keys:
--   community_id -> dim_community
--   created_date -> dim_date
--
-- Additional business dates such as tour_date, deposit_date
-- and move_in_date are retained for future analysis.


CREATE TABLE fact_unit_snapshot (
    unit_id VARCHAR,
    community_id VARCHAR,
    unit_type VARCHAR,
    monthly_rent DOUBLE,
    snapshot_date DATE
);

-- Grain: one unit per monthly snapshot.
-- Foreign keys:
--   unit_id       -> dim_unit
--   community_id  -> dim_community
--   snapshot_date -> dim_date


-- ============================================================
-- STAR SCHEMA RELATIONSHIP SUMMARY
-- ============================================================

-- dim_community 1:* fact_resident_month
-- dim_community 1:* fact_incident
-- dim_community 1:* fact_lease
-- dim_community 1:* fact_shift
-- dim_community 1:* fact_review
-- dim_community 1:* fact_lead
-- dim_community 1:* fact_unit_snapshot
--
-- dim_resident 1:* fact_resident_month
-- dim_resident 1:* fact_incident
-- dim_resident 1:* fact_lease
--
-- dim_unit 1:* fact_unit_snapshot
-- dim_unit 1:* fact_lease
--
-- dim_care_level 1:* fact_resident_month
--
-- dim_date 1:* fact_resident_month
-- dim_date 1:* fact_incident
-- dim_date 1:* fact_lease
-- dim_date 1:* fact_shift
-- dim_date 1:* fact_review
-- dim_date 1:* fact_lead
-- dim_date 1:* fact_unit_snapshot
--
-- Power BI relationships use single-direction filtering
-- from dimensions to fact tables.
--
-- No fact-to-fact relationships are used.
-- No dimension-to-dimension relationships are used.


-- ============================================================
-- NOTE
-- ============================================================

-- These CREATE TABLE statements document the analytical Gold
-- schema. The pipeline is responsible for creating/populating
-- the physical Gold tables from the Silver layer.